### ISSUE TITLE
Errors in Bills Under Purchases

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#612]
There is an error showing in Bills section under Purchases. Please see the following image:

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/2af399b8-da6b-477f-b3cd-4d6f35786f22)

1. Go to purchases, then go to bills section.
2. You will see the error.

**Comment by shsajalchowdhury** [comment]
Fixed
