### ISSUE TITLE
Form submission should be in Vendor table instead of Customer table and Customer title should be Vendor

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#613]
If we click on + icon of Vendor from "Add Expense" page, a modal opens. Here the title should be "Add Vendor" which is now "Add Customer" and when we submit the form, the data's are entered into customer table which should be in vendor table.

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/5835962a-4bed-49a0-b7c2-8236b7194142)

1. Go to Purchases, then go to Add Expense.
2. Click on + icon of vendor
3. You will see the "Add Customer" title.
4. When you submit the form, check whether the values are added as a vendor or not.
5. If you don't find the entered values into Vendor section, search it into the Customer.
6. You will find the error.

**Comment by shsajalchowdhury** [comment]
Improved the version.
