### ISSUE TITLE
Redirection and Success Message not showing problem after adding an expense

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#614]
When we want to add an expense, it gets added but does not redirect and doesn't show the success message. 

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/d3508060-841e-43ef-b9ac-e27b08d209de)

1. Go to purchases, then go to Add Expense
2. Try to submit the form.
3. You will find the error.

**Comment by shsajalchowdhury** [comment]
Improved the version. it's fixed.
