### ISSUE TITLE
Error in View Expense Page

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#615]
There is an error in View Expense page as shown in the following image:

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/664618ab-09f8-4d5b-af52-5a613a41f1d8)

1. Go to Purchases, then go to expenses.
2. Click on edit of any item.
3. Click on View expense button as shown in the following image

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/2a4b3ef1-34d4-40d2-b173-59bb0e59491b)

4. You will get the error.

**Comment by shsajalchowdhury** [comment]
Fixed
