### ISSUE TITLE
Banking> transfers is not working

### ISSUE THREAD

**Issue by owadud** [everaccounting/wp-ever-accounting#616]
We can't do the transfer. 

![image](https://github.com/everaccounting/wp-ever-accounting/assets/34317276/cdf8dd00-18aa-46f5-be82-f799069e32ff)

Procedure:

1. Go to "Banking" from the Accounting menu
2. Click on the "Transfers" section and then click on "Add transfer".
3. Fill up the all required field.
4. Finally click on "Save Transfer" and see the error.

**Comment by shsajalchowdhury** [comment]
Fixed
