### ISSUE TITLE
Not Showing Success Message when updating an expense item

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#617]
When we try to update an item of expense, it updates the item but does not show the success message.

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/c02b0695-38fa-42da-8e02-620c7c54ae5a)

1. Go to Purchases, then go to Expenses.
2. Click on Edit of any item.
3. Click on Save Expense button.
4. You won't see any success message.

**Comment by shsajalchowdhury** [comment]
Fixed and improved the version.
