### ISSUE TITLE
Two delete buttons are not working of Expense and redirection problem

### ISSUE THREAD

**Issue by RejwanAhmed** [everaccounting/wp-ever-accounting#618]
If we want to delete an expense item, it won't get deleted and redirects to another page. See the following two screenshots.

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/0da983da-d67b-49c4-bc63-06e523dc8432)

![image](https://github.com/everaccounting/wp-ever-accounting/assets/31104396/43cfb5f9-36fd-4303-85bb-9750a3fd6948)

First Problem:
1. Go to purchase, then go to expenses
2. Try to delete any item from the table
3. You will find the error.

Second Problem:
1. Go to purchase, then go to expenses.
2. Click on edit of any item.
3. Click on delete button.
4. You will find the error.

**Comment by shsajalchowdhury** [comment]
Version has been improved
