### ISSUE TITLE
Incorrect Article and Wording in Settings Field Descriptions

### ISSUE THREAD

**Issue by marufhossain92** [everaccounting/wp-ever-accounting#729]
In the Settings section, there are minor text issues in the descriptions for some text fields (under the [?] symbol).

1. Incorrect Article Usage (**Settings > Purchases > Bill Settings > Due Date**):
- Currently: Uses "an". Should use "a" to match proper grammatical usage.
![Screenshot_2](https://github.com/user-attachments/assets/7dd6080b-f932-4d69-987e-0372da2389d8)

2. Suggested Text Improvement (**Settings > General > Business Settings > ZIP**):
- The phrase "if any" can be displayed within brackets for clarity.
![Screenshot_1](https://github.com/user-attachments/assets/75827425-852c-4b74-930f-a748c1f16128)

**Comment by devsabbirhossain** [comment]
solved
