### ISSUE TITLE
UI and Calculation Issues in Invoice Section

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#732]
Several issues have been identified in the Invoice section:

1. Spacing Issue in Quantity Column:

- The x (cross) button in the Quantity column lacks proper spacing, causing visual clutter.
- Expected: There should be a space after the (x) button for improved readability.

2. Incorrect data in Price Column:

- Currently, the Price column displays the Cost instead of the Price of items.
- Expected: The Price column should correctly display the Price of items.

3. Incorrect Due Calculation (Excludes Tax):

- The Due amount is being calculated without including the Tax amount, resulting in an incorrect total.
- Expected: Due amount should include Tax for a correct final total.

![image (2)](https://github.com/user-attachments/assets/26b741cc-d86a-4223-bd27-b10599a23dae)

**Comment by devsabbirhossain** [comment]
solved
