### ISSUE TITLE
Wrong URL on Add customer button on Add Payment screen

### ISSUE THREAD

**Issue by romanbiswas** [everaccounting/wp-ever-accounting#733]
When the user clicks the '**Add Customer'** button on the '**Add Payment**' screen, they should be directed to the **'Add Customer'** screen. Currently, it redirects to the '**Add Expense**' screen instead.

Additionally Hovering on + Button from Add Payment Screen shows **'Add Vendor'**. It should say **'Add Customer'** https://i.imgur.com/vycTbgP.png

Step to reproduce:
1. Go to Accounting > Sales > Add Payment
2. Click on this button https://i.imgur.com/k3qhpee.png

**Comment by devsabbirhossain** [comment]
solved
