### ISSUE TITLE
Search Box Not Functioning Correctly in Invoices and Customers Tabs

### ISSUE THREAD

**Issue by marufhossain92** [everaccounting/wp-ever-accounting#734]
The search functionality is not working as expected in the Invoices and Customers sections of the plugin:

1. Non-Functional Search in Invoices and Customers Tabs:

- When attempting to use the search box in either the Invoices or Customers tabs, the search does not yield results or perform as expected.

2. Navigation Issue in Customers Tab After Search:

- When a search is performed in the Customers tab, the user is automatically redirected to the Customers tab view.

**Comment by devsabbirhossain** [comment]
solved
