### ISSUE TITLE
Date and Time Mismatch

### ISSUE THREAD

**Issue by romanbiswas** [everaccounting/wp-ever-accounting#736]
The displayed date and time are consistently 12 hours ahead of the actual time when first created. After reloading the page, the time increases by an additional 6 hours, resulting in a total discrepancy of 18 hours.

After adding the note: https://i.imgur.com/LiVJjG9.png
After reloading: https://i.imgur.com/6nhiPxE.png

Step to reproduce:
1. Accounting > Sales > Customer > View Customer > Note
2. Add note

**Comment by shsajalchowdhury** [comment]
The issue has been fixed. time remains the same after reloading.
