### ISSUE TITLE
Partial Payment Conversion Issue Leading to Minor Inaccuracy in Base Currency (BDT)

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#737]
When a partial payment is made in USD while the base currency is set to BDT, there is a minor discrepancy in the converted amount due to rounding issues in the conversion factor. This results in a few pennies being inaccurately added or missed in the converted BDT amount, affecting the overall accuracy.

Steps to Reproduce:

1. Set the base currency to BDT.
2. Make a partial payment in USD.
3. Make another partial payment in BDT.
4. Observe the converted BDT amount, where there is a minor discrepancy, with a few pennies less or more than the expected value.

**Expected Behavior**: The conversion should accurately reflect the amount in BDT with precise rounding to prevent penny discrepancies.

![Screenshot_5](https://github.com/user-attachments/assets/90241338-06bb-456d-8529-48cea10f0581)

**Comment by devsabbirhossain** [comment]
testing done and solved
