### ISSUE TITLE
Expense Method Not Displaying or Saving Correctly in Add/Edit Expense Section

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#739]
In the Add Expense or Edit Expense section, when an expense method is selected, it does not display correctly in the view section and shows as "N/A." Additionally, the selected expense method is not saved, causing a loss of information.

Steps to Reproduce:

1. Navigate to the Add Expense or Edit Expense section.
2. Select an expense method.
3. Save the entry and go to the view section.
4. Observe that the expense method displays as "N/A" and is not saved as expected.

**Expected Behavior**: The selected expense method should display accurately in the view section and be saved properly in the record.

![Screenshot_6](https://github.com/user-attachments/assets/bf59a78a-25ed-475b-af82-b1178c6bd5a8)

![Screenshot_7](https://github.com/user-attachments/assets/fe165588-4e9a-410a-90e6-6f312ff6661a)

**Comment by devsabbirhossain** [comment]
solved
