### ISSUE TITLE
Amount tooltip text on Add Payment and Add Expense is not reflecting Decimal Separator setting.

### ISSUE THREAD

**Issue by romanbiswas** [everaccounting/wp-ever-accounting#741]
- [x] Amount tooltip text on Add Payment and Add Expense is not reflecting Decimal Separator setting.

The decimal separator is comma (,) 
but the tooltip text is saying to use full stop (.) for decimal

https://i.imgur.com/d7AQlzi.png

**Comment by devsabbirhossain** [comment]
solved
