### ISSUE TITLE
Display Issue in Bill Column of Expenses Section

### ISSUE THREAD

**Issue by marufhossain92** [everaccounting/wp-ever-accounting#743]
In the **Expenses section**, there is a display issue in the Bill column where both the default "-" symbol and the Bill number appear simultaneously when a Bill number is present. This creates visual clutter and may confuse users.

Steps to Reproduce:

1. Navigate to the Expenses section.
2. View the Bill column with a Bill number.
3. Observe that both the "-" sign and the Bill number are displayed together.

**Expected Behavior**: Only the Bill number should be shown if present, and the "-" symbol should display only when there is no Bill number.

![Screenshot_8](https://github.com/user-attachments/assets/573fbc35-9013-453d-8888-5f66b3a91832)

**Comment by devsabbirhossain** [comment]
solved
