### ISSUE TITLE
Partial Payment Incorrectly Marked as Full Payment

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#751]
When making a partial payment on an invoice or bill, the system is incorrectly marking the full amount as paid, despite only a portion of the total amount being entered.

Steps to Reproduce:

1. Open an invoice or bill.
2. Attempt to pay a partial amount (e.g., half of the total).
3. Observe that the system records the entire amount as paid instead of only the partial amount entered.

Expected Behavior: The system should only record the exact partial amount entered, updating the outstanding balance accordingly, and should not mark the invoice or bill as fully paid until the total amount has been paid in full.

**Comment by devsabbirhossain** [comment]
Testing done and solved
