### ISSUE TITLE
Tax Rate and Compound Missing in Exported Tax Data

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#754]
In the export section, when exporting tax data, the tax rate and compound fields are not included in the exported file.

Steps to Reproduce:
1. Go to the export section.
2. Select tax data for export.
3. Review the exported file and observe that the tax rate and compound fields are missing.

Expected Behavior: The exported tax data should include all relevant fields, including the tax rate and compound, to provide a complete data set for users.

**Comment by devsabbirhossain** [comment]
Testing Done and Solved
