### ISSUE TITLE
"To Account" and "From Account" Displayed Incorrectly in Transfers Section

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#755]
In the Transfers section, the "To Account" and "From Account" fields are incorrectly displayed interchangeably in the table, causing confusion about the direction of funds. The labels should be switched to accurately reflect the source and destination of the transfer.

Steps to Reproduce:
1. Navigate to the Transfers section.
2. Create a transfer and assign accounts to "To Account" and "From Account."
3. Observe that in the table, the "To Account" and "From Account" are displayed incorrectly, appearing swapped.

Expected Behavior: The "To Account" should correctly display the destination account, and the "From Account" should display the source account, accurately reflecting the transfer direction.

![Screenshot_17](https://github.com/user-attachments/assets/f569bcec-63f2-45bc-97a5-0e3df522127f)

**Comment by devsabbirhossain** [comment]
Testing done and solved
