### ISSUE TITLE
Headers Not Excluded During Item Import

### ISSUE THREAD

**Issue by emarufh** [everaccounting/wp-ever-accounting#767]
When importing items, the import process includes the header row in the imported data instead of excluding it. This results in an unnecessary entry for the headers, leading to data cleanup requirements and potential errors in the items list.

Steps to Reproduce:
1. Go to the Import Items section.
2. Upload a csv file that includes headers as the first row.
3. Observe that the headers are imported as an item entry instead of being ignored.

Expected Behavior: The import process should automatically exclude the header row and only import data from subsequent rows, ensuring clean and accurate item entries.

**Comment by shsajalchowdhury** [comment]
The issue has been fixed and tested.
