### ISSUE TITLE
Invoice table need to be enhance to display items properly.

### ISSUE THREAD

**Issue by kawsarahmedr** [everaccounting/wp-ever-accounting#771]
There is an issue with the invoice - item list table, I the item has taxes then the table row goes break.

### Screenshot:
![image](https://github.com/user-attachments/assets/74ddd2d8-7b0e-4195-88b2-8ae25d9a5d39)

**Comment by shsajalchowdhury** [comment]
The issue has been fixed. 
![image](https://github.com/user-attachments/assets/4d7ffc8e-38c8-4416-aef0-5e252e667abf)
