### ISSUE TITLE
There is an issue while rendering Top Items inside the Dashboard!

### ISSUE THREAD

**Issue by kawsarahmedr** [everaccounting/wp-ever-accounting#773]
There is an issue while rendering Top Items inside the Dashboard!

Code Line: Dashboard.php:342 no. line

### Screenshots:

![image](https://github.com/user-attachments/assets/16c75a64-5dae-45d9-beb3-e7ad611b4866)

**Comment by shsajalchowdhury** [comment]
Top items have been showing. 
![image](https://github.com/user-attachments/assets/400bdfe8-b646-4434-b458-e9da529a1e34)
