### ISSUE TITLE
There is an currency exchange rate issue while upgrading

### ISSUE THREAD

**Issue by kawsarahmedr** [everaccounting/wp-ever-accounting#781]
The exchange rates are not migrated. Ever there are 5 PHP errors found in "Array to string conversion"

### Screenshot
![image](https://github.com/user-attachments/assets/06469780-4574-429e-8491-ae9c4b937cb6)

![image](https://github.com/user-attachments/assets/78d2dcb1-a005-4dc3-b775-e995cf5b9074)

**Comment by shsajalchowdhury** [comment]
The issue has been fixed.
