### ISSUE TITLE
Clicking on Add new button takes you to add tax

### ISSUE THREAD

**Issue by romanbiswas** [everaccounting/wp-ever-accounting#787]
After creating a transfer entry/ edit transfer window when clicking on "Add new" it takes you to the "Add tax" windows

https://prnt.sc/9GQIBpEH-Ien

/wp-admin/admin.php?page=eac-settings&tab=taxes&section=rates&action=add

**Comment by shsajalchowdhury** [comment]
Tested and it's fixed.
